### ISSUE TITLE
Can't build on bitrise

### ISSUE THREAD

**Issue by Langsdorf** [DataDog/dd-sdk-reactnative#265]
Thanks for taking the time for reporting an issue!

**Describe what happened**
Using `gradlew assembleRelease` in my machine works just fine, but when I try to build on bitrise, it won't work.

```
Build file '/Users/vagrant/git/node_modules/@datadog/mobile-react-native/android/build.gradle' line: 22

* What went wrong:
A problem occurred evaluating project ':datadog_mobile-react-native'.
> com.android.build.api.dsl.CommonExtension.getSourceSets()Lorg/gradle/api/NamedDomainObjectContainer;

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating project ':datadog_mobile-react-native'.
...
Caused by: java.lang.NoSuchMethodError: com.android.build.api.dsl.CommonExtension.getSourceSets()Lorg/gradle/api/NamedDomainObjectContainer;
	...

==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':datadog_mobile-react-native'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':datadog_mobile-react-native'.
	...
Caused by: com.android.builder.errors.EvalIssueException: compileSdkVersion is not specified. Please add it to build.gradle
	....

==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
```

`android/build.gradle`:
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "30.0.0"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
        supportLibVersion = "30.0.0"
        ndkVersion = "21.4.7075529"
        kotlin_version = '1.6.0'
        excludeAppGlideModule = true
    }
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath('com.android.tools.build:gradle:4.0.2')
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        classpath('com.google.gms:google-services:4.3.10')
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.8.0'
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }

        maven {
            url 'https://pkgs.dev.azure.com/PublicPackagesCS/Behavior/_packaging/BehaviorAnalytics.SDK/maven/v1'
            name 'BehaviorAnalytics.SDK.Android'
        }
    }
}
```

Using:
    "@datadog/mobile-react-native": "^1.1.0",
    "@datadog/mobile-react-navigation": "^1.1.0",

**Comment by louiszawadzki** [comment]
Hi @Langsdorf, thank you for reporting this.

So far it looks like you are indeed specifying a `compileSdkVersion` in your `build.gradle`, unlike what the error message is saying.
Could you share your Bitrise workflow as a yaml file as well so we could see if any step here could be the reason for this bug?

Thank you very much

**Comment by Langsdorf** [comment]
Hi @louiszawadzki, sorry for the waiting

```yml
Production-APK:
    steps:
    - set-java-version@1:
        inputs:
        - set_java_version: '8'
    - activate-ssh-key@4:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@6: {}
    - get-npm-package-version@1: {}
    - change-value@1:
        title: Install AppCenter
        inputs:
        - old_value: '"react-native":'
        - new_value: '"appcenter": "^4.2.0","appcenter-analytics": "^4.2.0","appcenter-crashes":
            "^4.2.0","react-native":'
        - show_file: 'true'
        - file: "$BITRISE_SOURCE_DIR/package.json"
    - change-android-versioncode-and-versionname@1:
        inputs:
        - new_version_name: "$NPM_PACKAGE_VERSION"
        - version_code_offset: '1'
        - build_gradle_path: "$BITRISE_SOURCE_DIR/android/app/build.gradle"
    - yarn@0: {}
    - install-missing-android-tools@3:
        inputs:
        - ndk_version: 21.4.7075529
        - gradlew_path: "$PROJECT_LOCATION/gradlew"
    - android-build@1:
        inputs:
        - project_location: "$BITRISE_SOURCE_DIR/android"
    - appcenter-deploy-android@2:
        inputs:
        - api_token: "$APP_CENTER_API_TOKEN"
        - owner_name: LighthouseApps
        - app_name: Sao-Joao-V2
        - distribution_group: Lighthouse
        - debug: 'yes'
        - app_path: "$BITRISE_APK_PATH"
    - deploy-to-bitrise-io@2:
        inputs:
        - deploy_path: "$BITRISE_APK_PATH"
```
